export const Actions = {
    ADDINGRIDIENTS:'ADDINGRIDIENTS',
    REMOVEINGRIDIENTS:'REMOVEINGRIDIENTS',
    SETINGREDIENTS:'SETINGREDIENTS',
    FETCHINGREDIENTSFAILED:'FETCHINGREDIENTSFAILED',
    PURCASE_BURGER_SUCCESS:'PURCASE_BURGER_SUCCESS',
    PURCASE_BURGER_INPROGRESS:'PURCASE_BURGER_INPROGRESS',
    PURACHASE_BURGER_FAILED:'PURACHASE_BURGER_FAILED',
    PURACHASE_INIT:'PURACHASE_INIT',
}

export const TotalPriceReducer = {
    ADDPRICE:'ADDPRICE',
    REDUCEPRICE:'REDUCEPRICE',
    RESETPRICE:'RESETPRICE'
}

