export const Actions = {
    ADDINGRIDIENTS:'ADDINGRIDIENTS',
    REMOVEINGRIDIENTS:'REMOVEINGRIDIENTS',
    SETINGREDIENTS:'SETINGREDIENTS',
    FETCHINGREDIENTSFAILED:'FETCHINGREDIENTSFAILED',
    PURCASE_BURGER_SUCCESS:'PURCASE_BURGER_SUCCESS',
    PURCASE_BURGER_INPROGRESS:'PURCASE_BURGER_INPROGRESS',
    PURACHASE_BURGER_FAILED:'PURACHASE_BURGER_FAILED',
    PURACHASE_INIT:'PURACHASE_INIT',
}

export const TotalPriceReducer = {
    ADDPRICE:'ADDPRICE',
    REDUCEPRICE:'REDUCEPRICE',
    RESETPRICE:'RESETPRICE'
}

export const OrdersActions = {
    FETCH_ORDERS:'FETCH_ORDERS',
    LOADING_ORDERS:'LOADING_ORDERS',
    ERROR_ORDERS:'ERROR_ORDERS'
}

export const authentication = {
    AUTH_START:'AUTH_START',
    AUTH_SUCCESS:'AUTH_SUCCESS',
    AUTH_FAILED:'AUTH_FAILED'
}

export const Token = {
    STORE_TOKEN:'STORE_TOKEN'
}
