export const Actions = {
    ADDINGRIDIENTS:'ADDINGRIDIENTS',
    REMOVEINGRIDIENTS:'REMOVEINGRIDIENTS',
    SETINGREDIENTS:'SETINGREDIENTS',
    SET_INIT_INGREDIENTS:'SET_INIT_INGREDIENTS',
    FETCHINGREDIENTSFAILED:'FETCHINGREDIENTSFAILED',
    PURCASE_BURGER_SUCCESS:'PURCASE_BURGER_SUCCESS',
    PURCASE_BURGER_INPROGRESS:'PURCASE_BURGER_INPROGRESS',
    PURCHASE_BURGER_START:'PURCHASE_BURGER_START',
    PURACHASE_BURGER_FAILED:'PURACHASE_BURGER_FAILED',
    PURACHASE_INIT:'PURACHASE_INIT',
}

export const TotalPriceReducer = {
    ADDPRICE:'ADDPRICE',
    REDUCEPRICE:'REDUCEPRICE',
    RESETPRICE:'RESETPRICE'
}

export const OrdersActions = {
    FETCH_ALL_ORDERS:'FETCH_ALL_ORDERS',
    FETCH_ORDERS:'FETCH_ORDERS',
    LOADING_ORDERS:'LOADING_ORDERS',
    ERROR_ORDERS:'ERROR_ORDERS'
}

export const authentication = {
    AUTH_START:'AUTH_START',
    AUTH_SUCCESS:'AUTH_SUCCESS',
    AUTH_FAILED:'AUTH_FAILED',
    AUTH_LOGOUT:'AUTH_LOGOUT',
    AUTH_USER:'AUTH_USER',
    AUTH_CHECK_STATE:'AUTH_CHECK_STATE',
    AUTH_INITIATE_LOGOUT:'AUTH_INITIATE_LOGOUT',
    AUTH_CHECK_TIMEOUT:'AUTH_CHECK_TIMEOUT',
    SET_AUTH_REDIRECT_PATH:'SET_AUTH_REDIRECT_PATH'
}

export const Token = {
    STORE_TOKEN:'STORE_TOKEN'
}
